application: let-share
version: 1
runtime: python27
api_version: 1

handlers:
- url: /js
  static_dir: statics/javascripts

- url: /css
  static_dir: statics/stylesheets

- url: /posts/new
  script: main.py
  login: required

- url: /assets/.*
  script: assets.py

- url: /.*
  script: main.py

threadsafe: no